###

POST http://localhost:8080/users
Content-Type: application/json;

{
    "id":3, "name": "Bold",

}

###

DELETE http://localhost:8080/user
Content-Type: application/json

{
    "id": "abd02523-23d9-402c-9a81-d5b81ac4a9d0"
}

###
get http://localhost:8080/users

